"""empty message

Revision ID: 1fa6f9dabd75
Revises: 0d23b21b9ee7
Create Date: 2023-07-28 14:34:39.898987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa6f9dabd75'
down_revision = '0d23b21b9ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cars', schema=None) as batch_op:
        batch_op.alter_column('owner_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cars', schema=None) as batch_op:
        batch_op.alter_column('owner_number',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
