"""empty message

Revision ID: 925c9c9d441e
Revises: 1fa6f9dabd75
Create Date: 2023-07-31 09:52:27.281374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925c9c9d441e'
down_revision = '1fa6f9dabd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=64), nullable=True),
    sa.Column('owner_number', sa.String(length=64), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Cars')
    op.drop_table('Mechanic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mechanic',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Mechanic_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Mechanic_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Cars',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Cars_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('owner_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('mechanic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['Mechanic.id'], name='Cars_mechanic_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Cars_pkey')
    )
    op.drop_table('cars')
    op.drop_table('mechanic')
    # ### end Alembic commands ###
